export const GLOSSARY = [
  { cat: 'dl', term: 'Receptive field', def: 'The region of the input that can influence one unit of a feature map. It grows with depth, kernel size, stride and dilation.', see: 'cnn' },
  { cat: 'dl', term: 'Weight sharing', def: 'Reusing the same kernel at every spatial position, which gives translation equivariance and a small parameter count.', see: 'cnn' },
  { cat: 'dl', term: 'Residual connection', def: 'A skip path y = x + F(x) that lets gradients flow unimpeded through very deep networks (ResNet, Transformer).', see: 'cnn' },
  { cat: 'dl', term: 'Momentum', def: 'An exponential moving average of past gradients that damps oscillation across ravines and speeds travel along them.', see: 'optim' },
  { cat: 'dl', term: 'Adam', def: 'Optimizer combining momentum with per-parameter adaptive step sizes from a running average of squared gradients, with bias correction.', see: 'optim' },
  { cat: 'dl', term: 'Learning-rate schedule', def: 'A rule for changing the learning rate during training: warmup, cosine decay, step decay, linear decay.', see: 'optim' },
  { cat: 'dl', term: 'Backprop through time (BPTT)', def: 'Backpropagation applied to an RNN unrolled across time steps; gradients are products of Jacobians over the sequence.', see: 'rnn' },
  { cat: 'dl', term: 'Vanishing / exploding gradient', def: 'Repeated multiplication by Jacobians with norm below / above 1 makes gradients shrink or blow up exponentially with depth or sequence length.', see: 'rnn' },
  { cat: 'dl', term: 'Gradient clipping', def: 'Rescaling the gradient when its norm exceeds a threshold to tame exploding gradients.', see: 'rnn' },
  { cat: 'dl', term: 'Cell state', def: 'The LSTM\'s long-term memory vector, updated additively under gate control so gradients can persist across many steps.', see: 'lstm' },
  { cat: 'dl', term: 'Gate', def: 'A sigmoid-valued vector in (0,1) multiplied element-wise to decide how much information to let through.', see: 'lstm' },
  { cat: 'dl', term: 'Update gate', def: 'GRU gate z that interpolates between the previous hidden state and the new candidate.', see: 'gru' },
  { cat: 'dl', term: 'Attention', def: 'A differentiable lookup: a query is compared with keys to give weights that average the values.', see: 'attention' },
  { cat: 'dl', term: 'Teacher forcing', def: 'Training a decoder by feeding it ground-truth previous tokens instead of its own predictions.', see: 'attention' },
  { cat: 'dl', term: 'Self-attention', def: 'Attention where queries, keys and values all come from the same sequence, letting every token read every other token.', see: 'transformer' },
  { cat: 'dl', term: 'Multi-head attention', def: 'Running h attention operations in parallel in lower-dimensional subspaces and concatenating the results.', see: 'transformer' },
  { cat: 'dl', term: 'Positional encoding', def: 'Information injected into token embeddings so an order-agnostic attention layer can use position (sinusoidal, learned, rotary).', see: 'transformer' },
  { cat: 'dl', term: 'Layer normalization', def: 'Normalizes each token\'s features to zero mean / unit variance and rescales with learned gain and bias. Pre-LN is standard.', see: 'transformer' },
  { cat: 'dl', term: 'Masked language modeling', def: 'BERT\'s pre-training objective: hide ~15% of tokens and predict them from bidirectional context.', see: 'bert' },
  { cat: 'dl', term: 'Fine-tuning', def: 'Continuing training of a pre-trained model on a smaller task-specific dataset.', see: 'bert' },
  { cat: 'dl', term: 'Causal mask', def: 'A lower-triangular attention mask preventing a token from attending to future positions.', see: 'gpt' },
  { cat: 'dl', term: 'Temperature', def: 'Divides logits before softmax: T<1 sharpens the distribution, T>1 flattens it.', see: 'gpt' },
  { cat: 'dl', term: 'Top-p (nucleus) sampling', def: 'Sample only from the smallest set of tokens whose cumulative probability exceeds p.', see: 'gpt' },
  { cat: 'dl', term: 'KV cache', def: 'Stored keys and values of past tokens so each new token costs O(n) attention rather than recomputing the whole prefix.', see: 'gpt' },
  { cat: 'dl', term: 'RoPE', def: 'Rotary position embedding: rotates query/key pairs by position-dependent angles so dot products depend only on relative offset.', see: 'modern' },
  { cat: 'dl', term: 'Grouped-query attention (GQA)', def: 'Several query heads share one key/value head, shrinking the KV cache.', see: 'modern' },
  { cat: 'dl', term: 'Mixture of Experts (MoE)', def: 'A layer with many expert FFNs where a router activates only the top-k per token, decoupling parameters from compute.', see: 'modern' },
  { cat: 'dl', term: 'LoRA', def: 'Low-rank adaptation: freeze W and learn a rank-r update BA, training far fewer parameters.', see: 'modern' },
  { cat: 'dl', term: 'Scaling law', def: 'Empirical power-law relationship between loss and parameters, data and compute.', see: 'modern' },

  { cat: 'cuda', term: 'Thread', def: 'The smallest unit of execution in CUDA; each runs the same kernel with its own indices and registers.', see: 'cuda-exec' },
  { cat: 'cuda', term: 'Block', def: 'A group of up to 1024 threads that run on one SM, can synchronize with __syncthreads() and share shared memory.', see: 'cuda-exec' },
  { cat: 'cuda', term: 'Grid', def: 'All blocks launched by one kernel invocation. Blocks are independent and can run in any order.', see: 'cuda-exec' },
  { cat: 'cuda', term: 'Warp', def: 'A group of 32 consecutive threads that execute in lockstep (SIMT). The real unit of scheduling.', see: 'cuda-exec' },
  { cat: 'cuda', term: 'Streaming multiprocessor (SM)', def: 'The GPU\'s compute tile: warp schedulers, CUDA cores, tensor cores, register file and shared memory.', see: 'cuda-exec' },
  { cat: 'cuda', term: 'Global memory', def: 'Off-chip DRAM (HBM/GDDR) visible to all threads; large, high-bandwidth and high-latency.', see: 'cuda-memory' },
  { cat: 'cuda', term: 'Shared memory', def: 'Fast on-chip, software-managed scratchpad shared by the threads of a block, organized in 32 banks.', see: 'cuda-tiled' },
  { cat: 'cuda', term: 'Roofline model', def: 'Performance is bounded by min(peak FLOPS, bandwidth × arithmetic intensity); tells you if a kernel is compute- or memory-bound.', see: 'cuda-memory' },
  { cat: 'cuda', term: 'Arithmetic intensity', def: 'FLOPs performed per byte moved to/from memory.', see: 'cuda-memory' },
  { cat: 'cuda', term: 'Tiling', def: 'Partitioning data into blocks that fit in fast memory so each global load is reused many times.', see: 'cuda-tiled' },
  { cat: 'cuda', term: 'Memory coalescing', def: 'When a warp\'s accesses fall in few contiguous segments, the hardware merges them into few transactions.', see: 'cuda-coalesce' },
  { cat: 'cuda', term: 'Bank conflict', def: 'Two threads of a warp access different addresses in the same shared-memory bank, serializing the access.', see: 'cuda-coalesce' },
  { cat: 'cuda', term: 'Warp divergence', def: 'Threads of one warp taking different branches; the paths are executed serially with inactive lanes masked.', see: 'cuda-warp' },
  { cat: 'cuda', term: '__shfl_down_sync', def: 'Warp primitive that reads a register from another lane with no shared memory.', see: 'cuda-warp' },
  { cat: 'cuda', term: 'Occupancy', def: 'Resident warps per SM divided by the maximum; limited by registers, shared memory, block size and block count.', see: 'cuda-occupancy' },
  { cat: 'cuda', term: 'Register spilling', def: 'When a kernel needs more registers than allowed, values spill to slow local memory.', see: 'cuda-occupancy' },
  { cat: 'cuda', term: 'Stream', def: 'An ordered queue of GPU operations; operations in different streams may overlap.', see: 'cuda-streams' },
  { cat: 'cuda', term: 'Pinned memory', def: 'Page-locked host memory that enables DMA and truly asynchronous copies.', see: 'cuda-streams' },
  { cat: 'cuda', term: 'Tensor Core', def: 'Hardware unit executing small matrix multiply-accumulate tiles (e.g. 16×16×16) per instruction in FP16/BF16/TF32/FP8.', see: 'cuda-flash' },
  { cat: 'cuda', term: 'FlashAttention', def: 'Exact attention computed in tiles with online softmax so the N×N score matrix never touches HBM.', see: 'cuda-flash' },
  { cat: 'cuda', term: 'Online softmax', def: 'A streaming algorithm that maintains running max and sum so softmax can be computed block by block.', see: 'cuda-flash' }
]
